### ISSUE TITLE
Make it easier to configure settings

### ISSUE THREAD

**Issue by Nyholm** [dmishh/SettingsBundle#31]
There is a very deep tree. A typical setting config looks like this: 

``` yaml
dmishh_settings:
    settings:
        my_first_setting:
            scope: user
            validation:
                type: number # any Symfony2 form type
                options: # options passed to form
                    required: false
                    attr: { class: 'my-class' }
                    constraints: # To make sure the data looks like you expect
                        Symfony\Component\Validator\Constraints\Range:
                            min: 1
                            max: 65535
```

I suggest to make it a bit more flat. Maybe something like: 
``` yaml
dmishh_settings:
    settings:
        my_first_setting:
            scope: user
            type: number # any Symfony2 form type
            options: # options passed to form
                required: false
                attr: { class: 'my-class' }
            constraints: # To make sure the data looks like you expect
                Symfony\Component\Validator\Constraints\Range:
                    min: 1
                    max: 65535
```

I've moved the `type` and `constraints` up one level and removed the `validation`. How do you feel about this change? Should I make a PR?
