### ISSUE TITLE
[RFC] Use TranslationBundle while editing Settings

### ISSUE THREAD

**Issue by Rvanlaak** [dmishh/SettingsBundle#38]
The backend to edit Settings is great, especially because it just uses the Symfony form component in a proper way.

Some of my Settings require translation, that's why I'd like to know you opinion on integrating the [`TranslationFormBundle`](https://github.com/a2lix/TranslationFormBundle) into your bundle. It will allow the `SettingsBundle` to introduce an optional config parameter:

```yml
dmishh_settings:
    settings:
        my_first_setting: 
            translatable: true
```
Can you maybe comment on the translation strategy to use? I'm using the `[KnpDoctrineExtension](https://github.com/KnpLabs/DoctrineBehaviors#translatable)` strategy in my application, which works great.
