### ISSUE TITLE
settings per entity

### ISSUE THREAD

**Issue by juanolon** [dmishh/SettingsBundle#51]
Hey,
nice bundle btw. i do have a question:
i would like to have different settings per user. On my project, we use different entities per user group. And each of them has different settings. The user entity already implements the `SettingsOwnerInterface` interface and `getSettingIdentifier()` returns different id's per user type. But all settings with scope "user" are being show to all users.

 So my question is, did i miss something? or is this the current behaviour of the scope "user"? if so, does adding a new config `namespace` to the scope "user", and then filter the settings per entity class would be a good approach? like this:

```yaml
dmishh_settings:
    settings:
        guide:
            scope: user
            namespace: 'My\Bundle\Entity\Student'
            validation:
                type: choice
                options:
                    choices:
                        - opt1
                        - opt2
                    required: false
                    expanded: true
                    attr:
                        class:  'form-group checkbox'
                    placeholder: false
```
