### ISSUE TITLE
Update BuildForm to use FQCN

### ISSUE THREAD

**Issue by Nyholm** [dmishh/SettingsBundle#72]
This is required to support sf 3.0. 

Does this mean we need to specify the FQCN in the config?

``` yaml
dmishh_settings:
    settings:
        my_first_setting:
            type: 'Symfony\Component\Form\Extension\Core\Type\IntegerType'
```

We maybe should have a converter somehow for some standard types.
