### ISSUE TITLE
Wrong/outdated code snippets in the docs

### ISSUE THREAD

**Issue by millenc** [dmishh/SettingsBundle#82]
I've just begun using this bundle and I've come across a few code snippets in the documentation that are wrong or outdated when compared to the current master. Proposed fixes in the pull request  #83:

### Resources/doc/installation.md

master:

```php
<?php

// in AppKernel::registerBundles()
$bundles = array(
    // ...
    new Dmishh\SettingsBundle\DmishhSettingsBundle(),
);
```
is missing the *Bundle* part of the namespace just before *SettingsBundle*.

Fixed:

```php
<?php

// in AppKernel::registerBundles()
$bundles = array(
    // ...
    new Dmishh\Bundle\SettingsBundle\DmishhSettingsBundle(),
);
```

### Resources/doc/advanced-configuration.md

master:

```yaml
dmishh_settings:
    template: DmishhSettingsBundle:Settings:manage.html.twig
    cache_service: null
    cache_lifetime: 3600
    security:
         manage_global_settings_role: ROLE_USER
         users_can_manage_own_settings: true
    serialization: php # database serialization mechanism (php|json)
    settings:
        my_first_setting:
            type: number # any Symfony form type
            options: # options passed to form
                required: false
            constraints:
                Symfony\Component\Validator\Constraints\Range:
                    min: 1
                    max: 65535
```
The *options* and *constraints* sections of *my_first_setting* appear directly below it but they should go below a *validation* section. Also the *constraints* section must go under the *options* section.

Fixed:

```yaml
dmishh_settings:
    template: DmishhSettingsBundle:Settings:manage.html.twig
    cache_service: null
    cache_lifetime: 3600
    security:
         manage_global_settings_role: ROLE_USER
         users_can_manage_own_settings: true
    serialization: php # database serialization mechanism (php|json)
    settings:
        my_first_setting:
        	validation:
	            type: number # any Symfony form type
	            options: # options passed to form
	                required: false
		            constraints:
		                Symfony\Component\Validator\Constraints\Range:
		                    min: 1
		                    max: 65535
```

master:

```yaml
dmishh_settings:
    settings:
        my_first_setting:
            type: text
            options:
                max_length: 15
            constraints:
                Symfony\Component\Validator\Constraints\Regex:
                    pattern: "/^\d+$/"
```

Fixed:

```yaml
dmishh_settings:
    settings:
        my_first_setting:
            validation:
                type: text
                options:
                    max_length: 15
                    constraints:
                        Symfony\Component\Validator\Constraints\Regex:
                            pattern: "/^\d+$/"
```

### Resources/doc/faq.md

master:

```yaml
dmishh_settings:
    settings:
        my_first_setting:
            options:
                required: false
```
same error as **Resources/doc/advanced-configuration.md**

fixed:

```yaml
dmishh_settings:
    settings:
        my_first_setting:
        	validation:
	            options:
	                required: false
```
