### ISSUE TITLE
Entity

### ISSUE THREAD

**Issue by Paktusin** [dmishh/SettingsBundle#97]
Hi. Its possible to save Entities in setting field ?
```
dmishh_settings:
    settings:
        project_filter:
            type: entity
            options: {class: AppBundle:Project, multiple: true, choice_label: name}
```

In this config it save, but then on form load (/settings/global) symfony throw error
> Entities passed to the choice field must be managed. Maybe persist them in the entity manager?

**Comment by Paktusin** [comment]
Solved
**choice_value: id**
```
dmishh_settings:
    settings:
        project_filter:
            type: entity
            options: {class: AppBundle:Project, multiple: true, choice_label: name, choice_value: id}
```
